package com.blacksite.clocker.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.blacksite.clocker.model.db.FaceDB;

import com.blacksite.clocker.model.db.FaceDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceDBDaoConfig;

    private final FaceDBDao faceDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceDBDaoConfig = daoConfigMap.get(FaceDBDao.class).clone();
        faceDBDaoConfig.initIdentityScope(type);

        faceDBDao = new FaceDBDao(faceDBDaoConfig, this);

        registerDao(FaceDB.class, faceDBDao);
    }
    
    public void clear() {
        faceDBDaoConfig.clearIdentityScope();
    }

    public FaceDBDao getFaceDBDao() {
        return faceDBDao;
    }

}
