package com.blacksite.clocker.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "hand".
*/
public class HandDBDao extends AbstractDao<HandDB, Long> {

    public static final String TABLENAME = "hand";

    /**
     * Properties of entity HandDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AnalogClock = new Property(1, Integer.class, "analogClock", false, "analog_clock");
        public final static Property AnalogClockWidget = new Property(2, Integer.class, "analogClockWidget", false, "analog_clock_widget");
        public final static Property Image = new Property(3, Integer.class, "image", false, "image");
        public final static Property Number = new Property(4, Integer.class, "number", false, "number");
    }


    public HandDBDao(DaoConfig config) {
        super(config);
    }
    
    public HandDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"hand\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"analog_clock\" INTEGER," + // 1: analogClock
                "\"analog_clock_widget\" INTEGER," + // 2: analogClockWidget
                "\"image\" INTEGER," + // 3: image
                "\"number\" INTEGER);"); // 4: number
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"hand\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HandDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer analogClock = entity.getAnalogClock();
        if (analogClock != null) {
            stmt.bindLong(2, analogClock);
        }
 
        Integer analogClockWidget = entity.getAnalogClockWidget();
        if (analogClockWidget != null) {
            stmt.bindLong(3, analogClockWidget);
        }
 
        Integer image = entity.getImage();
        if (image != null) {
            stmt.bindLong(4, image);
        }
 
        Integer number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(5, number);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HandDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer analogClock = entity.getAnalogClock();
        if (analogClock != null) {
            stmt.bindLong(2, analogClock);
        }
 
        Integer analogClockWidget = entity.getAnalogClockWidget();
        if (analogClockWidget != null) {
            stmt.bindLong(3, analogClockWidget);
        }
 
        Integer image = entity.getImage();
        if (image != null) {
            stmt.bindLong(4, image);
        }
 
        Integer number = entity.getNumber();
        if (number != null) {
            stmt.bindLong(5, number);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HandDB readEntity(Cursor cursor, int offset) {
        HandDB entity = new HandDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // analogClock
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // analogClockWidget
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // image
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4) // number
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HandDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAnalogClock(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAnalogClockWidget(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setImage(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNumber(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HandDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HandDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HandDB entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
